### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by BorisNikolic** [hyperoslo/Minced#20]
I am using wp-api.org WordPress REST API, and after I fetch all posts for the selected category from the API, and I "MINCE" do JSON, the key ID is lost from the new NSDictionary.
I think this is a bug.

**Comment by 3lvis** [comment]
@SirobChilokin Could you share the mentioned JSON and the method that you're using? Thanks <3

**Comment by BorisNikolic** [comment]
@3lvis this is the one example of post from WP: http://hastebin.com/woxofeqike
And the method was: `-(NSDictionary *)minced_JSONObjectKeysWithNonnulls;`
"ID": 525, is lost after Minced usage. I am using www.realm.io to store fetched data locally, and ID tag for my model appears to be `<null>` after I used

```
RLMPost *post= [RLMPost createOrUpdateInDefaultRealmWithValue:mincedJSONPost];
```

Thanks!

**Comment by 3lvis** [comment]
Hi @SirobChilokin,

Minced uses `NSString-HYPNetworking` to do it's conversion. Acronyms such as `ID` are treated in a different way and Minced instead of just removing `null` from ID, it is also converting `ID` to `id`.

 https://github.com/hyperoslo/NSString-HYPNetworking/blob/master/Source/NSString%2BHYPNetworking.m#L117-L120

This is what I got after mincing your `JSON`.

```
{
    author =     {
        avatar = "http://2.gravatar.com/avatar/5602f62c7f35f9fc35e9261f9b3c1707?s=96";
        description = "";
        firstName = "";
        id = 2;
        lastName = "";
        meta =         {
            links =             {
                archives = "http://www.thesourcemagazine.org/wp-json/users/2/posts";
                self = "http://www.thesourcemagazine.org/wp-json/users/2";
            };
        };
        name = mikiadmin;
        nickname = mikiadmin;
        registered = "2015-09-10T08:04:36+00:00";
        slug = mikiadmin;
        url = "";
        username = mikiadmin;
    };
    id = 525;
    status = publish;
    title = "Chile: Chilean students awarded Diploma of Excellence";
    type = post;
}
```

If you see, the `id` field is there, is just `id` instead of `ID`. Let me know if this is a problem for you or you can just use it like that. I could try to add a different behaviour.

**Comment by BorisNikolic** [comment]
@3lvis It was my mistake, I named the ID property wrong. Sorry for wasting your time, Minced is awesome :+1:  

I didn't realized that the minced JSON have all keys like old JSON, but on different order, that is why I thought it was a bug and that the ID tag is gone now... 

Thank you!

**Comment by 3lvis** [comment]
@SirobChilokin Don't worry, have a nice day :sunny:
